name: Actualitza partits i nota

on:
  schedule:
    - cron: '30 6 * * *'  # Executa cada dia a les 6:30 UTC
  workflow_dispatch:      # També pots executar-lo manualment

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositori
        uses: actions/checkout@v3

      - name: Instal·la Python i dependències
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instal·la llibreries necessàries
        run: |
          python -m pip install --upgrade pip
          pip install nba_api

      - name: Executa el script principal
        run: python main.py

      - name: Fes commit dels canvis
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Enjoyability_Index_Database.txt partits_del_dia.json nba_json_partits nba_json_jugadors nba_json_playbyplay
          git commit -m "🔄 Actualització automàtica de dades"
          git push
